model_params:
  name: 'VQVAE'              # model name
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25

data_params:
  data_path: "/isilon/datalake/gurcan_rsch/scratch/otoscope/Hao/compare_frame_selection/data/Auto_selected_new_all"           # total = 160 imgs
# data_path: "/isilon/datalake/gurcan_rsch/scratch/otoscope/Hao/compare_frame_selection/data/human_selected_new_all" 

  train_batch_size: 16
  val_batch_size:  16
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.001                             # adjust learning rate
  weight_decay: 0.0
  scheduler_gamma: 0.0
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: gpu
  devices: 1 
  max_epochs: 100                      # adjust epochs

logging_params:
  save_dir: "logs/"
  name: 'Autoscope_VQVAE'
